### ISSUE TITLE
Can't parse date from GitLab

### ISSUE THREAD

**Issue by ruscur** [joblift/gitlab-panorama#4]
When I start gitlab-panorama, it quickly fails with the following:

```
[de.joblift.service.gitlabpanorama.Application] Started Application in 4.237 seconds (JVM running for 5.25)
2019-03-26 15:47:00,709 ERROR [de.joblift.service.gitlabpanorama.gitlab.GitlabClient] Failed retrieving projects from gitlab
 com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.Instant` from String "2018-12-19T19:43:57.350+11:00": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '2018-12-19T19:43:57.350+11:00' could not be parsed at index 23
 at [Source: (StringReader); line: 1, column: 210] (through reference chain: java.lang.Object[][0]->de.joblift.service.gitlabpanorama.gitlab.model.GitlabProject["created_at"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
        at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:80)
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:212)
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:50)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at de.joblift.service.gitlabpanorama.gitlab.GitlabClient.retrieveProjects(GitlabClient.java:65)
        at de.joblift.service.gitlabpanorama.gitlab.GitlabClient.retrieveProjects(GitlabClient.java:83)
        at de.joblift.service.gitlabpanorama.gitlab.GitlabFullstateCollector.refresh(GitlabFullstateCollector.java:38)
        at de.joblift.service.gitlabpanorama.initialization.Initializer.lambda$init$0(Initializer.java:57)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.time.format.DateTimeParseException: Text '2018-12-19T19:43:57.350+11:00' could not be parsed at index 23
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:206)
        ... 13 common frames omitted
Exception in thread "init collect" java.lang.NullPointerException
        at de.joblift.service.gitlabpanorama.gitlab.GitlabFullstateCollector.refresh(GitlabFullstateCollector.java:39)
        at de.joblift.service.gitlabpanorama.initialization.Initializer.lambda$init$0(Initializer.java:57)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

Looks like Java's parser doesn't recognise the format that the GitLab API is returning.

**Comment by galan** [comment]
Hi @ruscur ,
thank you for your bugreport. I retrieve the API calls in a different format, but I already recognized that the gitlab api has some glitches in their date-formats.

Just to get a better understanding when gitlab does return which format:
* Do you use the self-hosted or cloud version?
* If self-hosted which version?
* Did you run gitlab-panorama with docker?

I extended the code to support such formats, please check if it does work now, thanks.

**Comment by ruscur** [comment]
This works, thanks!

- self-hosted GitLab CE 11.9.1, was running something a few months old but I updated it hoping it'd fix it and it didn't
- no docker, I was trying to but it was too much hassle trying to get my proxy settings into maven inside the container
